// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-saved-words.ts
import { createClient } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
function client(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_saved_words_default = defineTool({
  name: "list_saved_words",
  title: "List saved words",
  description: "List the signed-in user's saved LinguaScript flashcards (words and phrases), optionally filtered by language or SRS state.",
  inputSchema: {
    language: z.string().optional().describe("ISO language code, e.g. 'fr', 'es'."),
    state: z.enum(["red", "orange", "green"]).optional().describe("SRS deck state filter."),
    limit: z.number().int().min(1).max(200).optional().describe("Max rows (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language, state, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client(ctx).from("saved_words").select("word,translation,language,state,is_phrase,context,next_review,review_count").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit ?? 50);
    if (language) q = q.eq("language", language);
    if (state) q = q.eq("state", state);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { words: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/tools/get-progress.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
function client2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_progress_default = defineTool2({
  name: "get_progress",
  title: "Get learning progress",
  description: "Return the signed-in user's LinguaScript profile: learning language, native language, XP, streak, level, and counts of saved words per SRS state.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = client2(ctx);
    const uid = ctx.getUserId();
    const [{ data: profile }, { data: words }] = await Promise.all([
      sb.from("profiles").select("*").eq("id", uid).maybeSingle(),
      sb.from("saved_words").select("state").eq("user_id", uid)
    ]);
    const counts = { red: 0, orange: 0, green: 0, total: words?.length ?? 0 };
    for (const w of words ?? []) {
      const s = w.state;
      if (s === "red" || s === "orange" || s === "green") counts[s]++;
    }
    const result = { profile, saved_word_counts: counts };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/save-word.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
function client3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var save_word_default = defineTool3({
  name: "save_word",
  title: "Save a flashcard",
  description: "Save a word or phrase to the signed-in user's LinguaScript flashcards. Duplicates for the same word+language are skipped.",
  inputSchema: {
    word: z2.string().min(1).describe("The word or phrase to save."),
    language: z2.string().min(2).describe("ISO language code of the word, e.g. 'fr'."),
    translation: z2.string().optional().describe("Optional translation into the user's native language."),
    context: z2.string().optional().describe("Optional sentence the word appeared in."),
    is_phrase: z2.boolean().optional().describe("True if saving a full phrase rather than a single word.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: true, openWorldHint: false },
  handler: async ({ word, language, translation, context, is_phrase }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const sb = client3(ctx);
    const uid = ctx.getUserId();
    const normalized = word.trim().toLowerCase();
    const { data: existing } = await sb.from("saved_words").select("id").eq("user_id", uid).eq("word", normalized).eq("language", language).maybeSingle();
    if (existing) {
      return {
        content: [{ type: "text", text: `Already saved: ${normalized}` }],
        structuredContent: { saved: false, already: true, id: existing.id }
      };
    }
    const yesterday = new Date(Date.now() - 864e5).toISOString().split("T")[0];
    const { data, error } = await sb.from("saved_words").insert({
      user_id: uid,
      word: normalized,
      language,
      translation: translation ?? "",
      context: context ?? "",
      is_phrase: !!is_phrase,
      next_review: yesterday,
      interval_days: 0,
      review_count: 0,
      ease_factor: 2.5,
      state: "red"
    }).select("id").single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Saved: ${normalized}` }],
      structuredContent: { saved: true, id: data.id }
    };
  }
});

// src/lib/mcp/tools/list-films.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.100.1";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
function client4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_films_default = defineTool4({
  name: "list_films",
  title: "Browse LinguaScript content",
  description: "List LinguaScript video lessons from the shared catalog, optionally filtered by language, category, or difficulty.",
  inputSchema: {
    language: z3.string().optional().describe("ISO language code, e.g. 'fr'."),
    category: z3.string().optional().describe("Category slug, e.g. 'travel', 'news'."),
    difficulty: z3.enum(["A1", "A2", "B1", "B2", "C1", "C2"]).optional(),
    limit: z3.number().int().min(1).max(100).optional().describe("Max rows (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ language, category, difficulty, limit }, ctx) => {
    if (!ctx.isAuthenticated())
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    let q = client4(ctx).from("films").select("id,title,language,category,difficulty,youtube_id,description").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (language) q = q.eq("language", language);
    if (category) q = q.eq("category", category);
    if (difficulty) q = q.eq("difficulty", difficulty);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { films: data ?? [], count: data?.length ?? 0 }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ffephracinqeylfhqkiz";
var mcp_default = defineMcp({
  name: "linguascript-mcp",
  title: "LinguaScript",
  version: "0.1.0",
  instructions: "Tools for LinguaScript, a YouTube-based language learning app. Use `get_progress` to see the signed-in user's learning language, XP, streak, and flashcard deck sizes. Use `list_saved_words` to inspect their vocabulary, `save_word` to add a word or phrase to their flashcards, and `list_films` to browse the shared lesson catalog.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_saved_words_default, get_progress_default, save_word_default, list_films_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
