
REVOKE EXECUTE ON FUNCTION public.frequency_coverage(text) FROM anon;

INSERT INTO public.sentence_patterns (language, cefr_level, usage_rank, template, slots, explanation, example, example_translation) VALUES
-- FRENCH
('fr','a1',1,'C''est ___.','[{"name":"noun","type":"noun_or_phrase"}]','Identify or name something.','C''est un livre.','It''s a book.'),
('fr','a1',2,'Je suis ___.','[{"name":"adjective","type":"adjective_or_noun"}]','Say what or how you are.','Je suis fatigué.','I am tired.'),
('fr','a1',3,'J''ai ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say what you have.','J''ai une question.','I have a question.'),
('fr','a1',4,'Je voudrais ___, s''il vous plaît.','[{"name":"object","type":"noun_or_phrase"}]','Politely ask for something.','Je voudrais un café, s''il vous plaît.','I would like a coffee, please.'),
('fr','a1',5,'Je ne ___ pas.','[{"name":"verb","type":"verb"}]','Make a simple negative statement.','Je ne comprends pas.','I don''t understand.'),
('fr','a1',6,'Où est ___ ?','[{"name":"noun","type":"noun_or_phrase"}]','Ask where something is.','Où est la gare ?','Where is the station?'),
('fr','a1',7,'Il y a ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say that something exists or is present.','Il y a un problème.','There is a problem.'),
('fr','a1',8,'J''aime ___.','[{"name":"thing","type":"noun_or_verb"}]','Say what you like.','J''aime voyager.','I like travelling.'),
('fr','a2',9,'Hier, j''ai ___.','[{"name":"participle","type":"past_participle"}]','Talk about something you did in the past.','Hier, j''ai vu ce film.','Yesterday I saw that film.'),
('fr','a2',10,'Je vais ___.','[{"name":"verb","type":"infinitive"}]','Talk about what you are going to do.','Je vais partir demain.','I''m going to leave tomorrow.'),
('fr','a2',11,'Je dois ___.','[{"name":"verb","type":"infinitive"}]','Express obligation.','Je dois travailler ce soir.','I have to work tonight.'),
('fr','a2',12,'___ est plus ___ que ___.','[{"name":"subject","type":"noun"},{"name":"adjective","type":"adjective"},{"name":"comparison","type":"noun"}]','Compare two things.','Le train est plus rapide que le bus.','The train is faster than the bus.'),
('fr','a2',13,'Je ___ parce que ___.','[{"name":"clause","type":"clause"},{"name":"reason","type":"clause"}]','Give a reason.','Je reste parce que j''ai du travail.','I''m staying because I have work.'),
('fr','a2',14,'Est-ce que tu peux ___ ?','[{"name":"verb","type":"infinitive"}]','Ask someone to do something.','Est-ce que tu peux m''aider ?','Can you help me?'),
('fr','b1',15,'Je pense que ___.','[{"name":"clause","type":"clause"}]','Give an opinion.','Je pense que c''est une bonne idée.','I think it''s a good idea.'),
('fr','b1',16,'Si ___, je ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a condition and its result.','Si j''ai le temps, je viendrai.','If I have time, I''ll come.'),
('fr','b1',17,'Il faut que je ___.','[{"name":"verb","type":"subjunctive"}]','Express necessity with the subjunctive.','Il faut que je parte.','I need to leave.'),
('fr','b1',18,'Ce qui m''intéresse, c''est ___.','[{"name":"topic","type":"noun_or_phrase"}]','Highlight what matters to you.','Ce qui m''intéresse, c''est la musique.','What interests me is music.'),
('fr','b2',19,'Bien que ___, ___.','[{"name":"concession","type":"clause"},{"name":"main","type":"clause"}]','Concede a point before making yours.','Bien que ce soit difficile, ça vaut la peine.','Although it''s difficult, it''s worth it.'),
('fr','b2',20,'Si j''avais ___, je ___erais.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about an unreal or hypothetical situation.','Si j''avais plus d''argent, je voyagerais.','If I had more money, I would travel.'),
('fr','c1',21,'Non seulement ___, mais aussi ___.','[{"name":"first","type":"clause"},{"name":"second","type":"clause"}]','Add emphasis by stacking two points.','Non seulement il parle français, mais aussi russe.','Not only does he speak French, but also Russian.'),
('fr','c2',22,'Quoi qu''il en soit, ___.','[{"name":"clause","type":"clause"}]','Move past an objection in formal discussion.','Quoi qu''il en soit, la décision est prise.','Be that as it may, the decision is made.'),
-- SPANISH
('es','a1',1,'Es ___.','[{"name":"noun","type":"noun_or_phrase"}]','Identify or name something.','Es un libro.','It''s a book.'),
('es','a1',2,'Estoy ___.','[{"name":"adjective","type":"adjective"}]','Say how you feel right now.','Estoy cansado.','I am tired.'),
('es','a1',3,'Tengo ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say what you have.','Tengo una pregunta.','I have a question.'),
('es','a1',4,'Quisiera ___, por favor.','[{"name":"object","type":"noun_or_phrase"}]','Politely ask for something.','Quisiera un café, por favor.','I would like a coffee, please.'),
('es','a1',5,'No ___.','[{"name":"verb","type":"verb"}]','Make a simple negative statement.','No entiendo.','I don''t understand.'),
('es','a1',6,'¿Dónde está ___?','[{"name":"noun","type":"noun_or_phrase"}]','Ask where something is.','¿Dónde está la estación?','Where is the station?'),
('es','a1',7,'Hay ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say that something exists.','Hay un problema.','There is a problem.'),
('es','a1',8,'Me gusta ___.','[{"name":"thing","type":"noun_or_verb"}]','Say what you like.','Me gusta viajar.','I like travelling.'),
('es','a2',9,'Ayer ___.','[{"name":"verb","type":"past_tense"}]','Talk about something you did.','Ayer vi esa película.','Yesterday I saw that film.'),
('es','a2',10,'Voy a ___.','[{"name":"verb","type":"infinitive"}]','Talk about your plans.','Voy a salir mañana.','I''m going to leave tomorrow.'),
('es','a2',11,'Tengo que ___.','[{"name":"verb","type":"infinitive"}]','Express obligation.','Tengo que trabajar esta noche.','I have to work tonight.'),
('es','a2',12,'___ es más ___ que ___.','[{"name":"subject","type":"noun"},{"name":"adjective","type":"adjective"},{"name":"comparison","type":"noun"}]','Compare two things.','El tren es más rápido que el autobús.','The train is faster than the bus.'),
('es','a2',13,'___ porque ___.','[{"name":"clause","type":"clause"},{"name":"reason","type":"clause"}]','Give a reason.','Me quedo porque tengo trabajo.','I''m staying because I have work.'),
('es','a2',14,'¿Puedes ___?','[{"name":"verb","type":"infinitive"}]','Ask someone to do something.','¿Puedes ayudarme?','Can you help me?'),
('es','b1',15,'Creo que ___.','[{"name":"clause","type":"clause"}]','Give an opinion.','Creo que es buena idea.','I think it''s a good idea.'),
('es','b1',16,'Si ___, ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a condition and its result.','Si tengo tiempo, iré.','If I have time, I''ll go.'),
('es','b1',17,'Es necesario que ___.','[{"name":"verb","type":"subjunctive"}]','Express necessity with the subjunctive.','Es necesario que vengas.','It''s necessary that you come.'),
('es','b1',18,'Lo que me interesa es ___.','[{"name":"topic","type":"noun_or_phrase"}]','Highlight what matters to you.','Lo que me interesa es la música.','What interests me is music.'),
('es','b2',19,'Aunque ___, ___.','[{"name":"concession","type":"clause"},{"name":"main","type":"clause"}]','Concede a point before making yours.','Aunque sea difícil, vale la pena.','Although it''s difficult, it''s worth it.'),
('es','b2',20,'Si tuviera ___, ___ría.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a hypothetical situation.','Si tuviera más dinero, viajaría.','If I had more money, I would travel.'),
('es','c1',21,'No sólo ___, sino también ___.','[{"name":"first","type":"clause"},{"name":"second","type":"clause"}]','Stack two points for emphasis.','No sólo habla español, sino también ruso.','Not only does he speak Spanish, but also Russian.'),
('es','c2',22,'Sea como sea, ___.','[{"name":"clause","type":"clause"}]','Move past an objection in formal discussion.','Sea como sea, la decisión está tomada.','Be that as it may, the decision is made.'),
-- ITALIAN
('it','a1',1,'È ___.','[{"name":"noun","type":"noun_or_phrase"}]','Identify or name something.','È un libro.','It''s a book.'),
('it','a1',2,'Sono ___.','[{"name":"adjective","type":"adjective"}]','Say what or how you are.','Sono stanco.','I am tired.'),
('it','a1',3,'Ho ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say what you have.','Ho una domanda.','I have a question.'),
('it','a1',4,'Vorrei ___, per favore.','[{"name":"object","type":"noun_or_phrase"}]','Politely ask for something.','Vorrei un caffè, per favore.','I would like a coffee, please.'),
('it','a1',5,'Non ___.','[{"name":"verb","type":"verb"}]','Make a simple negative statement.','Non capisco.','I don''t understand.'),
('it','a1',6,'Dov''è ___?','[{"name":"noun","type":"noun_or_phrase"}]','Ask where something is.','Dov''è la stazione?','Where is the station?'),
('it','a1',7,'C''è ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say that something exists.','C''è un problema.','There is a problem.'),
('it','a1',8,'Mi piace ___.','[{"name":"thing","type":"noun_or_verb"}]','Say what you like.','Mi piace viaggiare.','I like travelling.'),
('it','a2',9,'Ieri ho ___.','[{"name":"participle","type":"past_participle"}]','Talk about something you did.','Ieri ho visto quel film.','Yesterday I saw that film.'),
('it','a2',10,'Sto per ___.','[{"name":"verb","type":"infinitive"}]','Say what you are about to do.','Sto per uscire.','I''m about to go out.'),
('it','a2',11,'Devo ___.','[{"name":"verb","type":"infinitive"}]','Express obligation.','Devo lavorare stasera.','I have to work tonight.'),
('it','a2',12,'___ è più ___ di ___.','[{"name":"subject","type":"noun"},{"name":"adjective","type":"adjective"},{"name":"comparison","type":"noun"}]','Compare two things.','Il treno è più veloce dell''autobus.','The train is faster than the bus.'),
('it','a2',13,'___ perché ___.','[{"name":"clause","type":"clause"},{"name":"reason","type":"clause"}]','Give a reason.','Resto perché ho del lavoro.','I''m staying because I have work.'),
('it','a2',14,'Puoi ___?','[{"name":"verb","type":"infinitive"}]','Ask someone to do something.','Puoi aiutarmi?','Can you help me?'),
('it','b1',15,'Penso che ___.','[{"name":"clause","type":"subjunctive_clause"}]','Give an opinion.','Penso che sia una buona idea.','I think it''s a good idea.'),
('it','b1',16,'Se ___, ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a condition and its result.','Se ho tempo, verrò.','If I have time, I''ll come.'),
('it','b1',17,'Bisogna che io ___.','[{"name":"verb","type":"subjunctive"}]','Express necessity.','Bisogna che io parta.','I need to leave.'),
('it','b1',18,'Quello che mi interessa è ___.','[{"name":"topic","type":"noun_or_phrase"}]','Highlight what matters to you.','Quello che mi interessa è la musica.','What interests me is music.'),
('it','b2',19,'Benché ___, ___.','[{"name":"concession","type":"clause"},{"name":"main","type":"clause"}]','Concede a point before making yours.','Benché sia difficile, ne vale la pena.','Although it''s difficult, it''s worth it.'),
('it','b2',20,'Se avessi ___, ___rei.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a hypothetical situation.','Se avessi più soldi, viaggerei.','If I had more money, I would travel.'),
('it','c1',21,'Non solo ___, ma anche ___.','[{"name":"first","type":"clause"},{"name":"second","type":"clause"}]','Stack two points for emphasis.','Non solo parla italiano, ma anche russo.','Not only does he speak Italian, but also Russian.'),
('it','c2',22,'Comunque sia, ___.','[{"name":"clause","type":"clause"}]','Move past an objection in formal discussion.','Comunque sia, la decisione è presa.','Be that as it may, the decision is made.'),
-- GERMAN
('de','a1',1,'Das ist ___.','[{"name":"noun","type":"noun_or_phrase"}]','Identify or name something.','Das ist ein Buch.','That is a book.'),
('de','a1',2,'Ich bin ___.','[{"name":"adjective","type":"adjective"}]','Say what or how you are.','Ich bin müde.','I am tired.'),
('de','a1',3,'Ich habe ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say what you have.','Ich habe eine Frage.','I have a question.'),
('de','a1',4,'Ich hätte gern ___, bitte.','[{"name":"object","type":"noun_or_phrase"}]','Politely ask for something.','Ich hätte gern einen Kaffee, bitte.','I would like a coffee, please.'),
('de','a1',5,'Ich ___ nicht.','[{"name":"verb","type":"verb"}]','Make a simple negative statement.','Ich verstehe nicht.','I don''t understand.'),
('de','a1',6,'Wo ist ___?','[{"name":"noun","type":"noun_or_phrase"}]','Ask where something is.','Wo ist der Bahnhof?','Where is the station?'),
('de','a1',7,'Es gibt ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say that something exists.','Es gibt ein Problem.','There is a problem.'),
('de','a1',8,'Ich mag ___.','[{"name":"thing","type":"noun"}]','Say what you like.','Ich mag Musik.','I like music.'),
('de','a2',9,'Gestern habe ich ___.','[{"name":"participle","type":"past_participle"}]','Talk about something you did.','Gestern habe ich den Film gesehen.','Yesterday I watched the film.'),
('de','a2',10,'Ich werde ___.','[{"name":"verb","type":"infinitive"}]','Talk about the future.','Ich werde morgen abreisen.','I will leave tomorrow.'),
('de','a2',11,'Ich muss ___.','[{"name":"verb","type":"infinitive"}]','Express obligation.','Ich muss heute Abend arbeiten.','I have to work tonight.'),
('de','a2',12,'___ ist ___er als ___.','[{"name":"subject","type":"noun"},{"name":"adjective","type":"adjective"},{"name":"comparison","type":"noun"}]','Compare two things.','Der Zug ist schneller als der Bus.','The train is faster than the bus.'),
('de','a2',13,'Ich ___, weil ___.','[{"name":"clause","type":"clause"},{"name":"reason","type":"verb_final_clause"}]','Give a reason with verb-final word order.','Ich bleibe, weil ich Arbeit habe.','I''m staying because I have work.'),
('de','a2',14,'Kannst du ___?','[{"name":"verb","type":"infinitive"}]','Ask someone to do something.','Kannst du mir helfen?','Can you help me?'),
('de','b1',15,'Ich denke, dass ___.','[{"name":"clause","type":"verb_final_clause"}]','Give an opinion.','Ich denke, dass es eine gute Idee ist.','I think that it''s a good idea.'),
('de','b1',16,'Wenn ___, dann ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a condition and its result.','Wenn ich Zeit habe, dann komme ich.','If I have time, I''ll come.'),
('de','b1',17,'Es ist wichtig, ___ zu ___.','[{"name":"object","type":"noun_or_phrase"},{"name":"verb","type":"infinitive"}]','Say what is important to do.','Es ist wichtig, jeden Tag zu üben.','It''s important to practise every day.'),
('de','b1',18,'Was mich interessiert, ist ___.','[{"name":"topic","type":"noun_or_phrase"}]','Highlight what matters to you.','Was mich interessiert, ist Musik.','What interests me is music.'),
('de','b2',19,'Obwohl ___, ___.','[{"name":"concession","type":"verb_final_clause"},{"name":"main","type":"clause"}]','Concede a point before making yours.','Obwohl es schwierig ist, lohnt es sich.','Although it''s difficult, it''s worth it.'),
('de','b2',20,'Wenn ich ___ hätte, würde ich ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"infinitive"}]','Talk about a hypothetical situation.','Wenn ich mehr Geld hätte, würde ich reisen.','If I had more money, I would travel.'),
('de','c1',21,'Nicht nur ___, sondern auch ___.','[{"name":"first","type":"clause"},{"name":"second","type":"clause"}]','Stack two points for emphasis.','Er spricht nicht nur Deutsch, sondern auch Russisch.','He speaks not only German, but also Russian.'),
('de','c2',22,'Wie dem auch sei, ___.','[{"name":"clause","type":"clause"}]','Move past an objection in formal discussion.','Wie dem auch sei, die Entscheidung ist gefallen.','Be that as it may, the decision has been made.'),
-- PORTUGUESE
('pt','a1',1,'É ___.','[{"name":"noun","type":"noun_or_phrase"}]','Identify or name something.','É um livro.','It''s a book.'),
('pt','a1',2,'Estou ___.','[{"name":"adjective","type":"adjective"}]','Say how you feel right now.','Estou cansado.','I am tired.'),
('pt','a1',3,'Tenho ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say what you have.','Tenho uma pergunta.','I have a question.'),
('pt','a1',4,'Queria ___, por favor.','[{"name":"object","type":"noun_or_phrase"}]','Politely ask for something.','Queria um café, por favor.','I would like a coffee, please.'),
('pt','a1',5,'Não ___.','[{"name":"verb","type":"verb"}]','Make a simple negative statement.','Não entendo.','I don''t understand.'),
('pt','a1',6,'Onde fica ___?','[{"name":"noun","type":"noun_or_phrase"}]','Ask where something is.','Onde fica a estação?','Where is the station?'),
('pt','a1',7,'Há ___.','[{"name":"noun","type":"noun_or_phrase"}]','Say that something exists.','Há um problema.','There is a problem.'),
('pt','a1',8,'Gosto de ___.','[{"name":"thing","type":"noun_or_verb"}]','Say what you like.','Gosto de viajar.','I like travelling.'),
('pt','a2',9,'Ontem ___.','[{"name":"verb","type":"past_tense"}]','Talk about something you did.','Ontem vi aquele filme.','Yesterday I saw that film.'),
('pt','a2',10,'Vou ___.','[{"name":"verb","type":"infinitive"}]','Talk about your plans.','Vou sair amanhã.','I''m going to leave tomorrow.'),
('pt','a2',11,'Tenho que ___.','[{"name":"verb","type":"infinitive"}]','Express obligation.','Tenho que trabalhar hoje à noite.','I have to work tonight.'),
('pt','a2',12,'___ é mais ___ do que ___.','[{"name":"subject","type":"noun"},{"name":"adjective","type":"adjective"},{"name":"comparison","type":"noun"}]','Compare two things.','O trem é mais rápido do que o ônibus.','The train is faster than the bus.'),
('pt','a2',13,'___ porque ___.','[{"name":"clause","type":"clause"},{"name":"reason","type":"clause"}]','Give a reason.','Fico porque tenho trabalho.','I''m staying because I have work.'),
('pt','a2',14,'Podes ___?','[{"name":"verb","type":"infinitive"}]','Ask someone to do something.','Podes ajudar-me?','Can you help me?'),
('pt','b1',15,'Acho que ___.','[{"name":"clause","type":"clause"}]','Give an opinion.','Acho que é uma boa ideia.','I think it''s a good idea.'),
('pt','b1',16,'Se ___, ___.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a condition and its result.','Se tiver tempo, eu vou.','If I have time, I''ll go.'),
('pt','b1',17,'É preciso que ___.','[{"name":"verb","type":"subjunctive"}]','Express necessity with the subjunctive.','É preciso que venhas.','You need to come.'),
('pt','b1',18,'O que me interessa é ___.','[{"name":"topic","type":"noun_or_phrase"}]','Highlight what matters to you.','O que me interessa é a música.','What interests me is music.'),
('pt','b2',19,'Embora ___, ___.','[{"name":"concession","type":"subjunctive_clause"},{"name":"main","type":"clause"}]','Concede a point before making yours.','Embora seja difícil, vale a pena.','Although it''s difficult, it''s worth it.'),
('pt','b2',20,'Se eu tivesse ___, ___ria.','[{"name":"condition","type":"clause"},{"name":"result","type":"clause"}]','Talk about a hypothetical situation.','Se eu tivesse mais dinheiro, viajaria.','If I had more money, I would travel.'),
('pt','c1',21,'Não só ___, mas também ___.','[{"name":"first","type":"clause"},{"name":"second","type":"clause"}]','Stack two points for emphasis.','Não só fala português, mas também russo.','Not only does he speak Portuguese, but also Russian.'),
('pt','c2',22,'Seja como for, ___.','[{"name":"clause","type":"clause"}]','Move past an objection in formal discussion.','Seja como for, a decisão está tomada.','Be that as it may, the decision is made.')
ON CONFLICT (language, template) DO NOTHING;
